---
abstract: 'create a Type::Tiny library of simpleTypes in .xsd files.'
author:
  - 'Renee Baecker <github@renee-baecker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TypeLibrary-FromXSD
requires:
  Capture::Tiny: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 0
  Moo: 0
  Test::More: 0
  XML::LibXML: 0
version: 0.02
